[[stack]]
name = "1password"
[stack.config]
server = "Local"
repo = "ClementPhan/komodo-stacks"
run_directory = "stacks/1password"
config_files = [
  { path = "1password-credentials.json", services = ["op-connect-api", "op-connect-sync"], requires = "Redeploy" }
]
pre_deploy.command = """
sh ../../inject_service_account.sh [[OP_SERVICE_ACCOUNT_TOKEN]]
"""
