[[stack]]
name = "audiobookshelf"
[stack.config]
server = "Local"
repo = "ClementPhan/komodo-stacks"
run_directory = "./stacks/audiobookshelf"
config_files = [
  { path = "config/Settings.json", services = ["libation"], requires = "Redeploy" },
  { path = "config/AccountsSettings.json", services = ["libation"], requires = "Redeploy" }
]
pre_deploy.command = """
sh ../../inject.sh [[OP_CONNECT_TOKEN]]
"""
