[[stack]]
name = "homebox"
[stack.config]
server = "Local"
git_account = "ClementPhan"
repo = "ClementPhan/komodo-stacks"
run_directory = "./stacks/homebox"
pre_deploy.command = """
sh ../../inject.sh [[OP_CONNECT_TOKEN]]
"""

