services:
  op-connect-api:
    container_name: op-connect-api
    image: 1password/connect-api:latest
    # ports:
    #   - "8080:8080"
    volumes:
      - "./1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - "data:/home/opuser/.op/data"
  op-connect-sync:
    image: 1password/connect-sync:latest
    # ports:
    #   - "8081:8080"
    volumes:
      - "./1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - "data:/home/opuser/.op/data"
  op-cli:
    container_name: op-cli
    image: 1password/op:latest
    tty: true # keep container running
    environment:
      - OP_CONNECT_HOST=http://op-connect-api:8080

volumes:
  data:
