- Network:
  - Komodo:
      icon: komodo.svg
      href: https://komodo.{{op://docker/home_address/url/url}}/
      description: Docker management
      server: my-docker
      container: ix-komodo-core-1
      widget:
        type: komodo
        url: https://komodo.{{op://docker/home_address/url/url}}
        key: {{op://docker/komodo/api/key}}
        secret: {{op://docker/komodo/api/secret}}
        showStacks: true
  - ISP Router:
      icon: router.svg
      href: http://box.{{op://docker/home_address/url/url}}/
      siteMonitor: https://box.{{op://docker/home_address/url/url}}
      description: Box Free
  - Home Assistant:
      icon: home-assistant.svg
      href: https://hub.{{op://docker/home_address/url/url}}
      siteMonitor: https://hub.{{op://docker/home_address/url/url}}
      description: Home automation
      widget:
        type: homeassistant
        url: https://hub.{{op://docker/home_address/url/url}}
        key: "{{op://docker/home_assistant/auth/token}}"
  - Emergency:
    - Komodo Override:
      icon: komodo.svg
      href: http://services.mammouth.{{op://docker/home_address/url/url}}:30160/
      description: Docker management when using the VPN
      server: my-docker
      container: ix-komodo-core-1

- NAS:
  - Gul Synology:
      icon: synology.svg
      href: https://gul.{{op://docker/home_address/url/url}}:5001/
      siteMonitor: https://gul.{{op://docker/home_address/url/url}}
      description: Synology DS220J
      widget:
        type: diskstation
        url: https://gul.{{op://docker/home_address/url/url}}:5001/
        username: {{op://docker/gul_remote_stats/username}}
        password: {{op://docker/gul_remote_stats/confirmpassword}}
        volume: volume_1
  - Mammouth TrueNAS:
      icon: truenas.svg
      href: https://mammouth.{{op://docker/home_address/url/url}}/
      description: TrueNAS Scale on Dell T420
